### ISSUE TITLE
Reply with Group Number and Class Section

### ISSUE THREAD

**Issue by ProfRojas** [dailesjsu/Project-1-Mileston-1#1]

**Comment by ProfRojas** [comment]
Also, just to verify that everyone created a GitHub account can you have all of your teammates post a message on this issue. They can just say hello.

**Comment by arashbnd** [comment]
Hello

**Comment by dailesjsu** [comment]
Hello

**Comment by jawnhoang** [comment]
hello

**Comment by JeffVong** [comment]
hello

**Comment by ProfRojas** [comment]
I also need to know your group number and class section.

**Comment by arashbnd** [comment]
group 6, section 5

**Comment by ProfRojas** [comment]
Thanks!
